---
title: "SDTEF - Homelessness Program Analysis"
author: "Brandon Miner"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr)
library(ggcorrplot)

dat = read.csv('data/processed/expenditures_and_PIT.csv')

head(dat)

# Sample data frame

standardize = function(col){
  col = (col - mean(col)) / sd(col)
  return(col)
}

dat_standard = dat |>
  select(City, Year, Unsheltered.PEH, Population, Grantee, Program, Amount, ExpenditureType) |>
  mutate(across(c(Year, Population, Amount), standardize))

head(dat_standard)
```

```{r correlation_check}
corr <- round(cor(
  dat |>
    select(Year, Unsheltered.PEH, Population, Amount)
), 1)

ggcorrplot(corr, hc.order = TRUE, type = "upper", outline.col = "white", lab = TRUE)
```

```{r linreg}
model = lm(Unsheltered.PEH ~ City + Year + Population + Program + Amount + Grantee, data = dat)
AIC(model)

model9 = lm(Unsheltered.PEH ~ Population + Program + Amount + Grantee + City, data = dat)
AIC(model9)

model9b = lm(Unsheltered.PEH ~ Population + Program + Amount + Grantee + City, data = dat_standard)
#modelX = lm(Unsheltered.PEH ~ Year + Population + Amount + Grantee)
#AIC(modelX)
# Winner
summary(model9)
```

```{r coeff_analysis}
coef_values <- coef(model9)

# Rank coefficients by absolute value, in descending order
ranked_coef <- sort(coef_values, decreasing = TRUE)

# View the ranked coefficients
print(formatC(ranked_coef, format = "f", digits = 4))

print("####################################################################################################################")

coef_values <- coef(model9b)

# Rank coefficients by absolute value, in descending order
ranked_coef <- sort(coef_values, decreasing = TRUE)

# View the ranked coefficients
print(formatC(ranked_coef, format = "f", digits = 4))
```
















